[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "indic_transformer"
version = "0.1.0"
description = "High-performance PyTorch multilingual transformer trained from scratch for Indic languages"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch",
    "tokenizers",
    "transformers",
    "datasets",
    "nltk",
    "pyyaml",
    "tqdm",
    "ipywidgets"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["indic_transformer*"]