project:
  name: "indic_transformer"
  seed: 42

language:
  target_language: "Hindi"
  dataset_name: "ai4bharat/samanantar"  # or 'cfilt/iitb-english-hindi', 'acomquest/Saamayik'
  tgt_lang: "hi"
  lang_pair: "EN-HI"

data:
  data_dir: "data"
  checkpoint_dir: "checkpoints"
  train_size: 50000
  test_size: 10000
  max_len: 80
  max_length_ratio: 6.0
  oversample: 6
  force_download: false

tokenizer:
  algo_src: "wordpiece"   # "bpe", "unigram", "wordpiece", "whitespace", "regex"
  algo_tgt: "bpe"
  max_vocab_size: 22400

model:
  d_model: 512
  num_layers: 6
  num_heads: 8
  d_ff: 2048
  dropout: 0.1

training:
  epochs: 10
  batch_size: 224
  lr: 5.0e-4
  weight_decay: 0.01
  label_smoothing: 0.1
  torch_compile: false
  gen_batch_size: 128
  bleu_sample: 300

inference:
  sample_sentences:
    - "this is a wonderful day"
    - "education is essential for every child"
    - "the water is very clean and cold"
    - "how are you doing today ?"
    - "farmers work hard in the field"